# This is a -*- Makefile -*-

ifeq ($(TARGET), redbee-econotag)
CFLAGS += -DLITTLE_ENDIAN=3412 -DBYTE_ORDER=LITTLE_ENDIAN
endif

ifeq ($(TARGET), wismote)
CFLAGS += -DLITTLE_ENDIAN=3412 -DBYTE_ORDER=LITTLE_ENDIAN
endif

ifeq ($(TARGET), exp5438)
CFLAGS += -DLITTLE_ENDIAN=3412 -DBYTE_ORDER=LITTLE_ENDIAN
endif

CFLAGS += -DDTLSv12 -DWITH_SHA256 -DSHA2_USE_INTTYPES_H=1

# This activates debugging support
# CFLAGS += -DNDEBUG
tinydtls_src += debug.c

